name: Deploy Static Site

concurrency:
  group: master-deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: ^7.25.0
      - uses: actions/setup-node@v3
        name: Setup NodeJS 18
        with:
          node-version: 18
          cache: pnpm
      - name: Build
        id: build-site
        run: |
          pnpm install
          pnpm generate
          echo "COMMIT_MSG=$(git log --format=reference -1)" >> $GITHUB_OUTPUT
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        name: Deploy
        with:
          folder: dist
          branch: gh-pages
          git-config-name: GitHub Action
          git-config-email: action@github.com
          commit-message: ${{ steps.build-site.outputs.COMMIT_MSG }}
          single-commit: true
